{% set name = "map2loop" %}


package:
  name: "{{ name|lower }}"
#   version: "{{ environ.get('GIT_DESCRIBE_TAG', '') }}"
  version: "1.3.2"

source:
  git_url: https://github.com/Loop3D/map2loop-2

build:
  number: 0
  script: "{{ PYTHON }} -m pip install ."

requirements:
  host:
    - pip
    - python
    # - pybind11
    - setuptools
  run:
    - python
    - numpy
    - pandas
    - geopandas
    - pyproj
    - shapely
    - rasterio<=1.2.10
    - descartes
    - matplotlib-base
    - networkx
    - scipy
    - owslib
    - tqdm
    - map2model
    - mplstereonet
    - hjson
    - loopprojectfile
    - beartype
    - cftime>=1.4.0

# test:
#   imports:
#     - map2loop

about:
  home: "https://github.com/Loop3D/map2loop-2"
  license: MIT
  license_family: MIT
  license_file: ../LICENSE
  summary: "Generate 3D model data using 2D maps."

extra:
  recipe-maintainers:
    - yohanderose
