{% set name = "map2loop" %}
{% set metadata = load_setup_py_data() %}

package:
  name: {{ name|lower }}
  version: {{ metadata.get('version') }}


source:
  git_url: https://github.com/Loop3D/map2loop-2

build:
  number: 0
  script: "{{ PYTHON }} -m pip install ."

requirements:
  host:
    - pip
    - python
    - pybind11
    - setuptools
  run:
    - python
    - numpy
    - pandas
    - geopandas
    - pyproj
    - shapely
    - rasterio
    - descartes
    - matplotlib-base
    - networkx
    - scipy
    - owslib
    - tqdm
    - map2model
    - mplstereonet
    - hjson
    - loopprojectfile
    - cftime=1.4.0

test:
  imports:
    - map2loop

about:
  home: "https://github.com/Loop3D/map2loop-2"
  license: MIT
  license_family: MIT
  license_file:
  summary: "Generate 3D model data using 2D maps."
  doc_url:
  dev_url:

extra:
  recipe-maintainers:
    - yohanderose
